//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDongHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apgia
    {
        public int ApgiaID { get; set; }
        public Nullable<int> LoaiapgiaID { get; set; }
        public Nullable<int> Denmuc { get; set; }
        public Nullable<int> Gia { get; set; }
    
        public virtual Loaiapgia Loaiapgia { get; set; }
    }
}
