//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDongHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chisonuoctheotuyen
    {
        public Chisonuoctheotuyen()
        {
            this.Chitietchisonuoctheotuyens = new HashSet<Chitietchisonuoctheotuyen>();
        }
    
        public int ChisonuocID { get; set; }
        public Nullable<int> DonghoID { get; set; }
        public Nullable<int> TuyenKHID { get; set; }
    
        public virtual ICollection<Chitietchisonuoctheotuyen> Chitietchisonuoctheotuyens { get; set; }
    }
}
