//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDongHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitiethoadonnuoc
    {
        public int ChitiethoadonnuocID { get; set; }
        public Nullable<int> HoadonnuocID { get; set; }
        public Nullable<int> Chisocu { get; set; }
        public Nullable<int> Chisomoi { get; set; }
        public Nullable<int> SH1 { get; set; }
        public Nullable<int> SH2 { get; set; }
        public Nullable<int> SH3 { get; set; }
        public Nullable<int> SH4 { get; set; }
        public Nullable<int> HC { get; set; }
        public Nullable<int> CC { get; set; }
        public Nullable<int> SXXD { get; set; }
        public Nullable<int> KDDV { get; set; }
    
        public virtual Hoadonnuoc Hoadonnuoc { get; set; }
    }
}
