//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDongHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chucnangchuongtrinh
    {
        public Chucnangchuongtrinh()
        {
            this.Lichsusudungcts = new HashSet<Lichsusudungct>();
            this.Quyens = new HashSet<Quyen>();
        }
    
        public int ChucnangID { get; set; }
        public Nullable<int> NhomchucnangID { get; set; }
        public string Ten { get; set; }
    
        public virtual Nhomchucnang Nhomchucnang { get; set; }
        public virtual ICollection<Lichsusudungct> Lichsusudungcts { get; set; }
        public virtual ICollection<Quyen> Quyens { get; set; }
    }
}
