//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDongHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Congno
    {
        public Congno()
        {
            this.Chitietcongnoes = new HashSet<Chitietcongno>();
        }
    
        public int CongnoID { get; set; }
        public Nullable<int> KhachhangID { get; set; }
        public Nullable<int> NhanvienID { get; set; }
        public Nullable<System.DateTime> Ngayghinhan { get; set; }
        public Nullable<int> Tongcongno { get; set; }
        public Nullable<int> Congnoquahan { get; set; }
    
        public virtual ICollection<Chitietcongno> Chitietcongnoes { get; set; }
        public virtual Khachhang Khachhang { get; set; }
        public virtual Nhanvien Nhanvien { get; set; }
    }
}
