//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDongHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donghotong
    {
        public Donghotong()
        {
            this.Kiemdinhs = new HashSet<Kiemdinh>();
        }
    
        public int DonghoID { get; set; }
        public Nullable<int> TuyenongID { get; set; }
        public Nullable<int> LoaidonghoID { get; set; }
        public Nullable<int> HangSXID { get; set; }
        public Nullable<int> Heso { get; set; }
        public Nullable<System.DateTime> Moclapdat { get; set; }
        public Nullable<double> Khoangcach { get; set; }
        public Nullable<double> Duongkinh { get; set; }
        public Nullable<int> Chisodau { get; set; }
        public string Sodolapdat { get; set; }
        public Nullable<int> Sothangbaohanh { get; set; }
        public string Ghichu { get; set; }
    
        public virtual Hangsanxuat Hangsanxuat { get; set; }
        public virtual Loaidongho Loaidongho { get; set; }
        public virtual Tuyenong Tuyenong { get; set; }
        public virtual ICollection<Kiemdinh> Kiemdinhs { get; set; }
    }
}
