//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDongHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khachhang
    {
        public Khachhang()
        {
            this.Chitietchisonuoctheotuyens = new HashSet<Chitietchisonuoctheotuyen>();
            this.Congnoes = new HashSet<Congno>();
            this.Hoadonnuocs = new HashSet<Hoadonnuoc>();
        }
    
        public int KhachhangID { get; set; }
        public Nullable<int> QuanhuyenID { get; set; }
        public Nullable<int> PhuongxaID { get; set; }
        public Nullable<int> CumdancuID { get; set; }
        public Nullable<int> TuyenKHID { get; set; }
        public Nullable<int> LoaiKHID { get; set; }
        public Nullable<int> LoaiapgiaID { get; set; }
        public Nullable<int> HinhthucttID { get; set; }
        public Nullable<int> TuyenongkythuatID { get; set; }
        public string Sotaikhoan { get; set; }
        public string Masothue { get; set; }
        public Nullable<System.DateTime> Ngaykyhopdong { get; set; }
        public Nullable<int> Tilephimoitruong { get; set; }
        public Nullable<int> Soho { get; set; }
        public Nullable<System.DateTime> Ngayap { get; set; }
        public Nullable<System.DateTime> Ngayhetap { get; set; }
        public Nullable<int> Sonhankhau { get; set; }
        public string Ten { get; set; }
        public string Diachi { get; set; }
        public string Dienthoai { get; set; }
        public string Ghichu { get; set; }
        public Nullable<int> Sokhuvuc { get; set; }
        public Nullable<int> Sohopdong { get; set; }
    
        public virtual ICollection<Chitietchisonuoctheotuyen> Chitietchisonuoctheotuyens { get; set; }
        public virtual ICollection<Congno> Congnoes { get; set; }
        public virtual Cumdancu Cumdancu { get; set; }
        public virtual Hinhthucthanhtoan Hinhthucthanhtoan { get; set; }
        public virtual ICollection<Hoadonnuoc> Hoadonnuocs { get; set; }
        public virtual Loaiapgia Loaiapgia { get; set; }
        public virtual LoaiKH LoaiKH { get; set; }
        public virtual Phuongxa Phuongxa { get; set; }
        public virtual Quanhuyen Quanhuyen { get; set; }
        public virtual Tuyenkhachhang Tuyenkhachhang { get; set; }
        public virtual Tuyenongkythuat Tuyenongkythuat { get; set; }
    }
}
