//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDongHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiemdinh
    {
        public int KiemdinhID { get; set; }
        public Nullable<int> LoaikiemdinhID { get; set; }
        public Nullable<int> DonghoID { get; set; }
        public Nullable<System.DateTime> Ngaykiemdinh { get; set; }
        public string Ghichu { get; set; }
    
        public virtual Donghotong Donghotong { get; set; }
        public virtual Loaikiemdinh Loaikiemdinh { get; set; }
    }
}
