//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDongHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loaikiemdinh
    {
        public Loaikiemdinh()
        {
            this.Kiemdinhs = new HashSet<Kiemdinh>();
        }
    
        public int LoaikiemdinhID { get; set; }
        public string Ten { get; set; }
    
        public virtual ICollection<Kiemdinh> Kiemdinhs { get; set; }
    }
}
