//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDongHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoidung
    {
        public Nguoidung()
        {
            this.Dangnhaps = new HashSet<Dangnhap>();
            this.Lichsusudungcts = new HashSet<Lichsusudungct>();
            this.Quyencuanguoidungs = new HashSet<Quyencuanguoidung>();
        }
    
        public int NguoidungID { get; set; }
        public Nullable<int> NhanvienID { get; set; }
        public string Taikhoan { get; set; }
        public string Matkhau { get; set; }
    
        public virtual ICollection<Dangnhap> Dangnhaps { get; set; }
        public virtual ICollection<Lichsusudungct> Lichsusudungcts { get; set; }
        public virtual Nhanvien Nhanvien { get; set; }
        public virtual ICollection<Quyencuanguoidung> Quyencuanguoidungs { get; set; }
    }
}
