//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDongHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhanvien
    {
        public Nhanvien()
        {
            this.Congnoes = new HashSet<Congno>();
            this.Hoadonnuocs = new HashSet<Hoadonnuoc>();
            this.Nguoidungs = new HashSet<Nguoidung>();
        }
    
        public int NhanvienID { get; set; }
        public Nullable<int> PhongbanID { get; set; }
        public Nullable<int> ChucvuID { get; set; }
        public string Ten { get; set; }
        public string SDT { get; set; }
        public string Diachi { get; set; }
    
        public virtual Chucvu Chucvu { get; set; }
        public virtual ICollection<Congno> Congnoes { get; set; }
        public virtual ICollection<Hoadonnuoc> Hoadonnuocs { get; set; }
        public virtual ICollection<Nguoidung> Nguoidungs { get; set; }
        public virtual Phongban Phongban { get; set; }
    }
}
