//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDongHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quanhuyen
    {
        public Quanhuyen()
        {
            this.Chinhanhs = new HashSet<Chinhanh>();
            this.Khachhangs = new HashSet<Khachhang>();
            this.Phuongxas = new HashSet<Phuongxa>();
        }
    
        public int QuanhuyenID { get; set; }
        public string Ten { get; set; }
    
        public virtual ICollection<Chinhanh> Chinhanhs { get; set; }
        public virtual ICollection<Khachhang> Khachhangs { get; set; }
        public virtual ICollection<Phuongxa> Phuongxas { get; set; }
    }
}
