//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDongHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuyenong
    {
        public Tuyenong()
        {
            this.Donghotongs = new HashSet<Donghotong>();
            this.Tuyenongkythuats = new HashSet<Tuyenongkythuat>();
        }
    
        public int TuyenongID { get; set; }
        public Nullable<int> TuyenongPID { get; set; }
        public Nullable<int> CaptuyenID { get; set; }
        public Nullable<int> Matuyen { get; set; }
        public string Tentuyen { get; set; }
    
        public virtual Captuyen Captuyen { get; set; }
        public virtual ICollection<Donghotong> Donghotongs { get; set; }
        public virtual ICollection<Tuyenongkythuat> Tuyenongkythuats { get; set; }
    }
}
