//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDongHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuyenongkythuat
    {
        public Tuyenongkythuat()
        {
            this.Khachhangs = new HashSet<Khachhang>();
        }
    
        public int TuyenongkythuatID { get; set; }
        public Nullable<int> TuyenongID { get; set; }
        public Nullable<int> Sohieu { get; set; }
    
        public virtual ICollection<Khachhang> Khachhangs { get; set; }
        public virtual Tuyenong Tuyenong { get; set; }
    }
}
